# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Global vagrant settings!

Vagrant.configure("2") do |config|
  # Just in case I ever decide to use cachier
  # Spoiler alert: I probably won't
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end

  # Configure hostmanager when available for my requisite hacky DNS
  # https://github.com/devopsgroup-io/vagrant-hostmanager
  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = false
  end

  config.vm.provider :virtualbox do |box|
    box.memory = '1024'
    box.cpus = '1'
    box.customize ['modifyvm', :id, '--audio', 'none'] # Keep VirtualBox from destroying my bluetooth audio quality
  end

  config.vm.provider :libvirt do |libvirt, override|
    libvirt.host = 'lab-local'
    libvirt.id_ssh_key_file = '/home/cwilson/.ssh/cwilson-home-kvm-cluster'
    libvirt.username = 'cwilson'
    libvirt.connect_via_ssh = true
    libvirt.management_network_device = 'br0'
    libvirt.cpus = '1'
    libvirt.memory = '1024'

    override.vm.synced_folder '.', '/vagrant', disabled: true
    override.ssh.insert_key = false
  end
end
