# -*- mode: ruby -*-
# vi: set ft=ruby :
#
# Global vagrant settings!

Vagrant.configure("2") do |config|
  # Just in case I ever decide to use cachier
  # Spoiler alert: I probably won't
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
  end

  # Configure hostmanager when available for my requisite hacky DNS
  # https://github.com/devopsgroup-io/vagrant-hostmanager
  if Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.manage_guest = true
    config.hostmanager.ignore_private_ip = false
    config.hostmanager.include_offline = false
  end

  config.vm.provider :virtualbox do |box|
    box.memory = '1024'
    box.cpus = '1'
  end
end
