# -*- mode: ruby -*-
# vi: set ft=ruby :
#
Vagrant.configure('2') do |config|
  config.vm.box = 'debian/stretch64'

  config.vm.define 'consul' do |c|
    c.vm.hostname = 'consul'
    c.vm.network :private_network, ip: '192.168.100.100'
    c.vm.provision :shell, inline: <<-SHELL
      apt-get install unzip
      wget -q https://releases.hashicorp.com/consul/1.0.6/consul_1.0.6_linux_amd64.zip
      unzip consul_1.0.6_linux_amd64.zip
    SHELL
  end

  config.vm.define 'vault' do |v|
    v.vm.hostname = 'vault'
    v.vm.network :private_network, ip: '192.168.100.101'
    v.vm.provision :shell, inline: <<-SHELL
      apt-get install unzip
      wget -q https://releases.hashicorp.com/vault/0.9.3/vault_0.9.3_linux_amd64.zip
      unzip vault_0.9.3_linux_amd64.zip
    SHELL
  end
end
