# -*- mode: ruby -*-
# vi: set ft=ruby :
#

postgres_ip = '192.168.150.100'
pgbouncer_ip = '192.168.150.101'

Vagrant.configure('2') do |config|
  config.vm.box = 'centos/7'

  config.vm.define 'postgres' do |postgres|
    postgres.vm.hostname = 'postgres'
    postgres.vm.network :private_network, ip: postgres_ip
    postgres.vm.provision :shell, inline: <<-SHELL
      echo "#{pgbouncer_ip} pgbouncer" > /etc/hosts
      rpm -Uvh https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-3.noarch.rpm
      yum install -y postgresql94-server postgresql94-contrib
    SHELL
  end

  config.vm.define 'pgbouncer' do |pgbouncer|
    pgbouncer.vm.hostname = 'pgbouncer'
    pgbouncer.vm.network :private_network, ip: pgbouncer_ip
    pgbouncer.vm.provision :shell, inline: <<-SHELL
      echo "#{postgres_ip} postgres" > /etc/hosts
      rpm -Uvh https://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-3.noarch.rpm
      yum install -y pgbouncer
    SHELL
  end
end
